export const CONNECT_TO_MONGO_TEST_REQUESTED = 'CONNECT_TO_MONGO_REQUESTED'
export const CONNECT_TO_MONGO_TEST_RECEIVED = 'CONNECT_TO_MONGO_RECEIVED'
export const CONNECT_TO_MONGO_TEST_FAILED = 'CONNECT_TO_MONGO_FAILED'